[project]
name = "task-guided-attention"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "einops>=0.8.2",
    "kornia>=0.8.3",
    "matplotlib>=3.11.2",
    "opencv-python>=5.0.0.93",
    "scikit-image>=0.26.0",
    "termcolor>=3.3.0",
    "timm==0.4.12",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.1",
    "wand>=0.7.2",
    "wandb>=0.30.0",
]
